# 用于本地安装的values.yaml
global:
  imageRegistry: "10.6.178.191:5000"
scheduler:
  patch:
    image:
      registry: "10.6.178.191:5000"
    imageNew:
      registry: "10.6.178.191:5000"
      repository: "library/kube-webhook-certgen"
      tag: "v1.1.1"
    enabled: false
  certManager:
    enabled: true